apiVersion: v1
kind: Service
metadata:
  name: bff-svc
spec:
  type: ClusterIP
  selector:
    app: bff
  ports:
    - name: nodejs
      port: 3000
      targetPort: nodejs
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sam-endpoint
  labels:
    app: endpoint
data:
  config.js: |-
    module.exports = {
        endpoint : {
            account: "http://api-svc:3001/",
            cms: "http://cms-svc:3002/"
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  labels:
    app: bff
    version: v1
spec:
  selector:
    matchLabels:
      app: bff
      version: v1
  replicas: 2
  template:
    metadata:
      name: bff
      labels:
        app: bff
        version: v1
    spec:
      containers:
        - name: bff
          image: g3.skb:8500/btv/bff:latest
          imagePullPolicy: Always
          volumeMounts:
          - name: app-config
            mountPath: /app/config.js
            subPath: "config.js"
          ports:
          - name: nodejs
            containerPort: 3000
          resources:
            requests:
              cpu: 300m
              memory: 500Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
          livenessProbe:
            httpGet:
              path: /health
              port: nodejs
            initialDelaySeconds: 5
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /health
              port: nodejs
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
      - name: app-config
        configMap:
          name: sam-endpoint
          items:
          - key: config.js
            path: config.js
            